ID = "id"
SIGLA = "sigla"
NOMBRE = "nombre"
PERMITE_RETIRO = "permite_retiro"
APROB_ESPECIAL = "aprob_especial"
AREA = "area"
CREDITOS = "creditos"
DESCRIPCION = "descripcion"

ID_CURSO = "id_curso"
SECCION = "seccion"
NRC = "nrc"
PROFESOR = "profesor"
CAMPUS = "campus"
EN_INGLES = "en_ingles"
HORARIO = "horario"
FORMATO = "formato"
SECCIONES = "secciones"

CATEDRA = "CLAS"
LAB = "LAB"
AYUDANTIA = "AYU"
TALLER = "TAL"