ID = "id"
SIGLA = "sigla"
NOMBRE = "nombre"
PERMITE_RETIRO = "permite_retiro"
APROB_ESPECIAL = "aprob_especial"
AREA = "area"
CREDITOS = "creditos"
DESCRIPCION = "descripcion"

ID_CURSO = "id_curso"
SECCION = "seccion"
NRC = "nrc"
PROFESOR = "profesor"
CAMPUS = "campus"
EN_INGLES = "en_ingles"
HORARIO = "horario"
FORMATO = "formato"
SECCIONES = "secciones"

NRCS = "nrcs"
PROFESORES = "profesores"
CAMPUSES = "campuses"
FORMATOS = "formatos"

SIGLA_CATEDRA = "CLAS"
SIGLA_LAB = "LAB"
SIGLA_AYUDANTIA = "AYU"
SIGLA_TALLER = "TAL"

TODAS = 0
